name: Pipeline de produção
env: 
   NODE_ENV: production
   VERCEL_ORG_ID: $({secrets.VERCEL_ORG_ID})
   VERCEL_PROJECT_ID: $({secrets.VERCEL_PROJECT_ID})


on: 
  push: 
      branches:
        - main


jobs: 

  job1:
    name: CI - Build e criação do artefato
    runs-on: ubuntu-latest
    steps:
      - name: Pegar código do Repositório
        uses: actions/checkout@v3

      - name: Instalação pacotes npm
        run: npm install
      
      - name: apagar pasta node_modules
        run: rm -rf node_modules

      - name: Apagar pasta .git
        run: rm -rf .git

      - name: Arquivos e pastas
        run: ls

      - name: Criando artefato ZIP do código buildado
        uses: actions/upload-artifact@v3
        with:
          name: artefato
          retention-days: 1
          path: ./


  job2: 
    name: CD - Deploy na Vercel
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Baixando Artefato do código buildado
        uses: actions/download-artifact@v3
        with: 
          name: artefato

      - name: Instalação pacotes npm
        run: npm install

      - name: Arquivos e pastas do arterfatos
        run: ls
        
      - name: Instalando CLI da Vercel
        run: npm install --global vercel@latest

      - name: Buscando informações de ambiente no Vercel
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod  --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy do projeto e artefatos na Vercel
        run: vercel deploy --prebuilt --prod  --token=${{ secrets.VERCEL_TOKEN }}